application: alertable
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/.+
  script: message.py

- url: /_ah/xmpp/.+
  script: message.py

- url: .*
  script: main.py

inbound_services:
- mail
- xmpp_message